server:
  port: 9991

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://211.157.164.162:13307/cgdb_v2.0?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456


elasticsearch:
  address: 192.168.200.36:9200
